name: montreal_tourist
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_svg: ^1.0.0
  hexcolor: ^3.0.1
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.1.0
  loading_animation_widget: ^1.2.0+4

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^4.0.6

  # Storage
  shared_preferences: ^2.0.15

  # Utilities
  device_preview: ^1.1.0
  loader_overlay: ^4.0.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4
  awesome_dialog: ^3.1.0
  connectivity_plus: ^5.0.2

  google_maps_flutter: ^2.10.0
  location:
  geolocator:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inder
      fonts:
        - asset: assets/fonts/Inder-Regular.ttf
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InriaSans-Light.ttf
          weight: 500
        - asset: assets/fonts/InriaSans-LightItalic.ttf
          weight: 500
        - asset: assets/fonts/InriaSans-Italic.ttf
          weight: 600
        - asset: assets/fonts/InriaSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 800
